FROM golang:1.27.1-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -tags timetzdata -o /app/cmd/bookshelfapp/exe /app/cmd/bookshelfapp

FROM alpine:3.24
WORKDIR /app
COPY --from=builder  /app/cmd/bookshelfapp/exe /app
CMD ["/app/exe"]