// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "Get a paginated list of books, optionally filtered by title/author",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List books",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by author",
                        "name": "author",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Books found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_books_transport_http.BookDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "Get book by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Get book",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book found",
                        "schema": {
                            "$ref": "#/definitions/internal_features_books_transport_http.GetBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/books/{id}/reviews": {
            "get": {
                "description": "Get a paginated list of reviews for a book",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List book reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reviews found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_books_transport_http.ReviewDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reviews": {
            "get": {
                "description": "Get the latest written reviews of all users together with their books, newest first (by read date)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "List recent reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reviews found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_books_transport_http.RecentReviewDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Get system-wide statistics by default; pass user_id for per-user statistics or book_id for per-book statistics (mutually exclusive, response shape returned is GetStatsResponse/GetUserStatsResponse/GetBookStatsResponse respectively)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Get statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Get statistics for this user instead of system-wide (mutually exclusive with book_id)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get statistics for this book instead of system-wide (mutually exclusive with user_id)",
                        "name": "book_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of top books to return (system statistics only)",
                        "name": "top",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter from date, format YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to date, format YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "System statistics",
                        "schema": {
                            "$ref": "#/definitions/internal_features_statistics_transport_http.GetStatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User or book not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get a paginated list of users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Users found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_users_transport_http.UserDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new user in the app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "CreateUser request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successed to create user",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get user by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User found",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete user by ID",
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successed to delete user"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially update user fields\n###Logic of updating fields:\n1. **If a field is provided in the request**: it will be updated with the new value.\n2. **If a field is not provided in the request**: it will remain unchanged.\n3. **If a field is provided with a null value**: it will result in a 400 error.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Patch user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchUser request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successed to patch user",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchedUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/activity": {
            "get": {
                "description": "Get a paginated list of the user's bookshelf activity events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookshelf"
                ],
                "summary": "Get user activity feed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Activity events found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_bookshelf_transport_http.EventDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/bookshelf": {
            "get": {
                "description": "Get a paginated list of books on the user's bookshelf, optionally filtered by read status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookshelf"
                ],
                "summary": "List bookshelf books",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by read status",
                        "name": "read",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Books found",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_bookshelf_transport_http.ShelfBookWithBookDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a book to the user's bookshelf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookshelf"
                ],
                "summary": "Add book to bookshelf",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AddBook request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_bookshelf_transport_http.AddBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successed to add book to bookshelf",
                        "schema": {
                            "$ref": "#/definitions/internal_features_bookshelf_transport_http.AddBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User or book not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/bookshelf/{book_id}": {
            "get": {
                "description": "Get a book from the user's bookshelf",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookshelf"
                ],
                "summary": "Get book from bookshelf",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book found",
                        "schema": {
                            "$ref": "#/definitions/internal_features_bookshelf_transport_http.GetBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found on bookshelf",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a book from the user's bookshelf",
                "tags": [
                    "bookshelf"
                ],
                "summary": "Remove book from bookshelf",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successed to remove book from bookshelf"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found on bookshelf",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially update a book on the user's bookshelf (read status, rating, review)\n###Logic of updating fields:\n1. **If a field is provided in the request**: it will be updated with the new value.\n2. **If a field is not provided in the request**: it will remain unchanged.\n3. **If ` + "`" + `read` + "`" + ` is provided with a null value**: it will result in a 400 error.\n4. **If ` + "`" + `rating` + "`" + ` or ` + "`" + `review` + "`" + ` is provided with a null value**: the field will be cleared.\n5. **` + "`" + `rating` + "`" + `/` + "`" + `review` + "`" + ` can only be set when the book is read** (` + "`" + `read=true` + "`" + `), otherwise a 409 error is returned.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookshelf"
                ],
                "summary": "Patch bookshelf book",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Book ID",
                        "name": "book_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchBook request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_bookshelf_transport_http.PatchShelfBookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successed to patch book",
                        "schema": {
                            "$ref": "#/definitions/internal_features_bookshelf_transport_http.PatchBookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Book not found on bookshelf",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Doomed07_Bookshelf_internal_core_transport_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid argument"
                },
                "message": {
                    "type": "string",
                    "example": "the provided argument is invalid"
                }
            }
        },
        "github_com_Doomed07_Bookshelf_internal_features_books_transport_http.BookDTOResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Дж. Р. Р. Толкин"
                },
                "description": {
                    "type": "string",
                    "example": "Повесть о путешествии хоббита Бильбо Бэггинса, втянутого в опасное приключение с гномами и драконом."
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Фэнтези",
                        "Приключения"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "type": "integer",
                    "example": 310
                },
                "reads_count": {
                    "type": "integer",
                    "example": 42
                },
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "title": {
                    "type": "string",
                    "example": "Хоббит, или Туда и обратно"
                },
                "year": {
                    "type": "integer",
                    "example": 1937
                }
            }
        },
        "internal_features_books_transport_http.BookDTOResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Дж. Р. Р. Толкин"
                },
                "description": {
                    "type": "string",
                    "example": "Повесть о путешествии хоббита Бильбо Бэггинса, втянутого в опасное приключение с гномами и драконом."
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Фэнтези",
                        "Приключения"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "type": "integer",
                    "example": 310
                },
                "reads_count": {
                    "type": "integer",
                    "example": 42
                },
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "title": {
                    "type": "string",
                    "example": "Хоббит, или Туда и обратно"
                },
                "year": {
                    "type": "integer",
                    "example": 1937
                }
            }
        },
        "internal_features_books_transport_http.GetBookResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Дж. Р. Р. Толкин"
                },
                "description": {
                    "type": "string",
                    "example": "Повесть о путешествии хоббита Бильбо Бэггинса, втянутого в опасное приключение с гномами и драконом."
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Фэнтези",
                        "Приключения"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "type": "integer",
                    "example": 310
                },
                "reads_count": {
                    "type": "integer",
                    "example": 42
                },
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "title": {
                    "type": "string",
                    "example": "Хоббит, или Туда и обратно"
                },
                "year": {
                    "type": "integer",
                    "example": 1937
                }
            }
        },
        "internal_features_books_transport_http.RecentReviewDTOResponse": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/internal_features_books_transport_http.BookDTOResponse"
                },
                "review": {
                    "$ref": "#/definitions/internal_features_books_transport_http.ReviewDTOResponse"
                }
            }
        },
        "internal_features_books_transport_http.ReviewDTOResponse": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "read_at": {
                    "type": "string",
                    "example": "2026-01-15T12:00:00Z"
                },
                "review": {
                    "type": "string",
                    "example": "Одна из лучших книг, что я читал."
                },
                "reviewed_at": {
                    "type": "string",
                    "example": "2026-01-20T18:30:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                }
            }
        },
        "internal_features_bookshelf_transport_http.AddBookRequest": {
            "type": "object",
            "required": [
                "book_id"
            ],
            "properties": {
                "book_id": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                }
            }
        },
        "internal_features_bookshelf_transport_http.AddBookResponse": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_features_books_transport_http.BookDTOResponse"
                },
                "shelf": {
                    "$ref": "#/definitions/internal_features_bookshelf_transport_http.ShelfBookDTOResponse"
                }
            }
        },
        "internal_features_bookshelf_transport_http.EventDTO": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "string",
                    "example": "2026-01-15T12:00:00Z"
                },
                "author": {
                    "type": "string",
                    "example": "Дж. Р. Р. Толкин"
                },
                "book_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "finished"
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "review": {
                    "type": "string",
                    "example": "Одна из лучших книг, что я читал."
                },
                "title": {
                    "type": "string",
                    "example": "Хоббит, или Туда и обратно"
                }
            }
        },
        "internal_features_bookshelf_transport_http.GetBookResponse": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_features_books_transport_http.BookDTOResponse"
                },
                "shelf": {
                    "$ref": "#/definitions/internal_features_bookshelf_transport_http.ShelfBookDTOResponse"
                }
            }
        },
        "internal_features_bookshelf_transport_http.PatchBookResponse": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_features_books_transport_http.BookDTOResponse"
                },
                "shelf": {
                    "$ref": "#/definitions/internal_features_bookshelf_transport_http.ShelfBookDTOResponse"
                }
            }
        },
        "internal_features_bookshelf_transport_http.PatchShelfBookRequest": {
            "type": "object",
            "properties": {
                "rating": {
                    "type": "integer",
                    "example": 80
                },
                "read": {
                    "type": "boolean",
                    "example": true
                },
                "review": {
                    "type": "string",
                    "example": "Одна из лучших книг, что я читал."
                }
            }
        },
        "internal_features_bookshelf_transport_http.ShelfBookDTOResponse": {
            "type": "object",
            "properties": {
                "added_at": {
                    "type": "string",
                    "example": "2026-01-10T09:00:00Z"
                },
                "book_id": {
                    "type": "integer",
                    "example": 1
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "read": {
                    "type": "boolean",
                    "example": true
                },
                "read_at": {
                    "type": "string",
                    "example": "2026-01-15T12:00:00Z"
                },
                "review": {
                    "type": "string",
                    "example": "Одна из лучших книг, что я читал."
                },
                "reviewed_at": {
                    "type": "string",
                    "example": "2026-01-20T18:30:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_bookshelf_transport_http.ShelfBookWithBookDTOResponse": {
            "type": "object",
            "properties": {
                "book": {
                    "$ref": "#/definitions/github_com_Doomed07_Bookshelf_internal_features_books_transport_http.BookDTOResponse"
                },
                "shelf": {
                    "$ref": "#/definitions/internal_features_bookshelf_transport_http.ShelfBookDTOResponse"
                }
            }
        },
        "internal_features_statistics_transport_http.BookDTOResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string",
                    "example": "Дж. Р. Р. Толкин"
                },
                "description": {
                    "type": "string",
                    "example": "Повесть о путешествии хоббита Бильбо Бэггинса, втянутого в опасное приключение с гномами и драконом."
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Фэнтези",
                        "Приключения"
                    ]
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "type": "integer",
                    "example": 310
                },
                "reads_count": {
                    "type": "integer",
                    "example": 42
                },
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "title": {
                    "type": "string",
                    "example": "Хоббит, или Туда и обратно"
                },
                "year": {
                    "type": "integer",
                    "example": 1937
                }
            }
        },
        "internal_features_statistics_transport_http.GetStatsResponse": {
            "type": "object",
            "properties": {
                "books_count": {
                    "type": "integer",
                    "example": 1022
                },
                "books_on_shelves": {
                    "type": "integer",
                    "example": 3450
                },
                "reads_count": {
                    "type": "integer",
                    "example": 2130
                },
                "top_by_reads": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_features_statistics_transport_http.BookDTOResponse"
                    }
                },
                "top_by_score": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_features_statistics_transport_http.BookDTOResponse"
                    }
                },
                "users_count": {
                    "type": "integer",
                    "example": 128
                }
            }
        },
        "internal_features_users_transport_http.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lol@mail.com"
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                }
            }
        },
        "internal_features_users_transport_http.CreateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lol@mail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.GetUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lol@mail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.PatchUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "Max@mail.com"
                },
                "username": {
                    "type": "string",
                    "example": "booklover"
                }
            }
        },
        "internal_features_users_transport_http.PatchedUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lol@mail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.UserDTOResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lol@mail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "book_worm07"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Bookshelf API",
	Description:      "Bookshelf Application REST-API schema",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
